application: gplus2others
version: 1
runtime: go
api_version: go1 

builtins:
    - remote_api: on

handlers:
- url: /static
  static_dir: static
- url: /sync
  script: _go_app
  login: admin
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /.*
  script: _go_app
